// Questions Index
// Auto-generated by split_questions_by_subject.py

import { Question } from '../types';

// Available subjects
export const AVAILABLE_SUBJECTS = [
  "anatomy",  "anesthesiology",  "biochemistry",  "dermatology",  "ent",  "forensic-medicine",  "medicine",  "microbiology",  "obgyn",  "ophthalmology",  "orthopedics",  "pathology",  "pediatrics",  "pharmacology",  "physiology",  "preventive-medicine",  "psychiatry",  "radiology",  "surgery",  "unknown"
] as const;

export type AvailableSubject = typeof AVAILABLE_SUBJECTS[number];

// Re-export lazy loading utilities
export * from '../../utils/questionLoader';

// Legacy export (for backward compatibility)
// Note: This loads ALL questions at once. Use lazy loading for better performance.
export async function loadAllQuestions(): Promise<Question[]> {
  const allQuestions: Question[] = [];
  
  for (const subject of AVAILABLE_SUBJECTS) {
    try {
      const module = await import(`./${subject}.ts`);
      allQuestions.push(...(module.questions || module.default || []));
    } catch (error) {
      console.error(`Failed to load questions for ${subject}:`, error);
    }
  }
  
  return allQuestions;
}

// Question counts per subject
export const QUESTION_COUNTS = {
  "anatomy": 20,  "anesthesiology": 3,  "biochemistry": 29,  "dermatology": 4,  "ent": 6,  "forensic-medicine": 12,  "medicine": 51,  "microbiology": 13,  "obgyn": 18,  "ophthalmology": 8,  "orthopedics": 6,  "pathology": 17,  "pediatrics": 10,  "pharmacology": 13,  "physiology": 14,  "preventive-medicine": 15,  "psychiatry": 5,  "radiology": 4,  "surgery": 67,  "unknown": 4
} as const;

export const TOTAL_QUESTIONS = 319;
