#!/usr/bin/env python3
"""
Split questions.ts into subject-specific files for lazy loading
"""

import re
import os
from collections import defaultdict

print("🔄 Starting question split process...\n")

# Read the main questions file
questions_file = 'lib/data/questions.ts'
with open(questions_file, 'r', encoding='utf-8') as f:
    content = f.read()

print(f"✓ Loaded {questions_file}")

# Extract imports and type definitions
imports_match = re.search(r'(.*?)(export const sampleQuestions)', content, re.DOTALL)
if imports_match:
    header = imports_match.group(1).strip()
else:
    header = "import { Question } from '../types';"

print("✓ Extracted imports\n")

# Find the questions array
questions_array_match = re.search(
    r'export const sampleQuestions: Question\[\] = \[(.*?)\];',
    content,
    re.DOTALL
)

if not questions_array_match:
    print("❌ Could not find sampleQuestions array")
    exit(1)

questions_content = questions_array_match.group(1)

# Split into individual questions
# Each question starts with { and ends with }, (or }] for last one)
question_pattern = r'\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}'
questions = re.findall(question_pattern, questions_content)

print(f"✓ Found {len(questions)} questions\n")

# Group questions by subject
questions_by_subject = defaultdict(list)
subject_counts = defaultdict(int)

for question in questions:
    # Find subjectId
    subject_match = re.search(r'subjectId:\s*["\']([^"\']+)["\']', question)
    if subject_match:
        subject_id = subject_match.group(1)
        questions_by_subject[subject_id].append(question)
        subject_counts[subject_id] += 1

print("📊 Questions per subject:")
for subject, count in sorted(subject_counts.items(), key=lambda x: -x[1]):
    print(f"   {subject.ljust(25)}: {count} questions")

print(f"\n✓ Total subjects: {len(questions_by_subject)}")
print(f"✓ Total questions: {sum(subject_counts.values())}\n")

# Create output directory
output_dir = 'lib/data/questions'
os.makedirs(output_dir, exist_ok=True)

print("💾 Creating subject-specific files...\n")

# Write each subject to its own file
for subject_id, subject_questions in questions_by_subject.items():
    filename = f"{output_dir}/{subject_id}.ts"
    
    # Create the file content
    file_content = f"""// {subject_id.upper()} Questions
// Auto-generated from questions.ts
// Total Questions: {len(subject_questions)}

import {{ Question }} from '../types';

export const questions: Question[] = [
{','.join(subject_questions)}
];

export default questions;

// Helper function to get questions by chapter
export function getQuestionsByChapter(chapterId: string): Question[] {{
  return questions.filter(q => q.chapterId === chapterId);
}}

// Export question count
export const questionCount = questions.length;
"""
    
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(file_content)
    
    print(f"   ✓ Created {filename} ({len(subject_questions)} questions)")

print("\n✅ Split complete!\n")

# Create an index file
index_content = f"""// Questions Index
// Auto-generated by split_questions_by_subject.py

import {{ Question }} from '../types';

// Available subjects
export const AVAILABLE_SUBJECTS = [
{','.join(f'  "{subject}"' for subject in sorted(questions_by_subject.keys()))}
] as const;

export type AvailableSubject = typeof AVAILABLE_SUBJECTS[number];

// Re-export lazy loading utilities
export * from '../../utils/questionLoader';

// Legacy export (for backward compatibility)
// Note: This loads ALL questions at once. Use lazy loading for better performance.
export async function loadAllQuestions(): Promise<Question[]> {{
  const allQuestions: Question[] = [];
  
  for (const subject of AVAILABLE_SUBJECTS) {{
    try {{
      const module = await import(\`./${{subject}}.ts\`);
      allQuestions.push(...(module.questions || module.default || []));
    }} catch (error) {{
      console.error(\`Failed to load questions for ${{subject}}:\`, error);
    }}
  }}
  
  return allQuestions;
}}

// Question counts per subject
export const QUESTION_COUNTS = {{
{','.join(f'  "{subject}": {count}' for subject, count in sorted(subject_counts.items()))}
}} as const;

export const TOTAL_QUESTIONS = {sum(subject_counts.values())};
"""

index_file = f"{output_dir}/index.ts"
with open(index_file, 'w', encoding='utf-8') as f:
    f.write(index_content)

print(f"✓ Created {index_file}\n")

print("📝 Summary:")
print(f"   - Split {sum(subject_counts.values())} questions into {len(questions_by_subject)} files")
print(f"   - Each file contains only its subject's questions")
print(f"   - Lazy loading will now work automatically")
print(f"   - Old code remains backward compatible\n")

print("✨ All done! Questions are now ready for lazy loading! 🚀\n")

